version: "3.9"
services:
  web_api:
    build: . # build the Docker image 
    container_name: auth_microservice
    ports:
      - "5001:80"
    depends_on:
      - sql-server-docker
      - elasticsearch
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server-docker;Database=Auth.MicroService.Database;User Id=sa;Password=A&VeryComplex123Password;TrustServerCertificate=True
      - Elasticsearch__Url=http://elasticsearch:9200
  sql-server-docker:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql-server-docker
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
    volumes:
      - sql_data:/var/opt/mssql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.15
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
volumes:
  sql_data:
  esdata: