apiVersion: v1
kind: ConfigMap
metadata:
 name: elasticsearch-config
data:
 elasticsearch.yml: |
   cluster.name: my-cluster
   node.name: node-1
   network.host: 0.0.0.0
   discovery.type: single-node
